### ISSUE TITLE
Install Issue 

### ISSUE THREAD

**Issue by HDVinnie** [faustbrian/Laravel-Friendable#11]
- Version: laravel 5.4
- PHP Version: 7.1

## Expected behavior:
For it to install properly

## Actual behavior:
Declaration of BrianFaust\Friendable\FriendableServiceProvider::boot(): BrianFaust\Friendable\void must be compatible with BrianFaust\ServiceProvider\AbstractServiceProvider::boot(): BrianFaust\ServiceProvider\void

## Steps to reproduce the behavior:
 composer require faustbrian/laravel-friendable
within app/config/app.php.
BrianFaust\Friendable\FriendableServiceProvider::class,
Migrate
php artisan vendor:publish --provider="BrianFaust\Friendable\FriendableServiceProvider" && php artisan migrate
## Proposed solution:
?

**Comment by faustbrian** [comment]
Looks like you are not on PHP 7.1 because it looks for the void return type under a namespace. That would not happen if you would be running on PHP 7.1.

Just tested it myself with a fresh Laravel 5.4 Application on PHP 7.1 and everything works fine.

**Comment by HDVinnie** [comment]
I am on 7.1. Here:

$php -v

```
PHP 7.1.3-3+deb.sury.org~yakkety+1 (cli) (built: Mar 25 2017 14:01:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-3+deb.sury.org~yakkety+1, Copyright (c) 1999-2017, by Zend Technologies
```

$php artisan --version

` Laravel Framework 5.4.17`

**Comment by faustbrian** [comment]
Well I am not able to reproduce your error on my local machine or production server with the latest version and the error is simply that PHP doesn’t recognise the void return type which is caused by issued with the PHP installation usually.
