### ISSUE TITLE
A function with return type must return a value

### ISSUE THREAD

**Issue by syropian** [faustbrian/Laravel-Friendable#13]
- Version: ^2.1
- PHP Version:  7.1.2-3+deb.sury.org~xenial+1

## Expected behavior: 

For the code to run without errors

## Actual behavior: 

`A function with return type must return a value in /vendor/faustbrian/laravel-friendable/src/HasFriends.php`

## Steps to reproduce the behavior: 

Run through the install instructions in the doc, try and run your code I guess?

## Proposed solution: 

A few functions seem to be expecting a boolean returned but you're doing an implicit void return, eg. `return;` in various methods. I assume these functions should return a boolean.

**Comment by faustbrian** [comment]
You're welcome to send a PR.
