### ISSUE TITLE
ErrorException in Friendable.php line 250:

### ISSUE THREAD

**Issue by maximusblade** [faustbrian/Laravel-Friendable#3]
# Issue / Motivation:

ErrorException in Friendable.php line 250: Argument 1 passed to App\User::findFriendship() must be an instance of Illuminate\Database\Eloquent\Model, null given, 

Just finished installing the package
my controller 
        $user = User::find(1);
        $pending_friendships = $user->getPendingFriendships();
        dd($friendships);

**Comment by d4rkd0s** [comment]
@maximusblade Are you sure there is a User being returned from the find?

Try this first:
```
dd($user);
```

Also your code is incorrect, here is the correct dd:
```
$user = User::find(1);
$pending_friendships = $user->getPendingFriendships();
dd($pending_friendships);
```
